// <copyright file="ClosedCaptionTrackInfo.cs" company="Drastic Actions">
// Copyright (c) Drastic Actions. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

namespace Drastic.YouTube.Videos.ClosedCaptions;

/// <summary>
/// Metadata associated with a closed caption track of a YouTube video.
/// </summary>
public class ClosedCaptionTrackInfo
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ClosedCaptionTrackInfo"/> class.
    /// Initializes an instance of <see cref="ClosedCaptionTrackInfo" />.
    /// </summary>
    public ClosedCaptionTrackInfo(string url, Language language, bool isAutoGenerated)
    {
        this.Url = url;
        this.Language = language;
        this.IsAutoGenerated = isAutoGenerated;
    }

    /// <summary>
    /// Gets track URL.
    /// </summary>
    public string Url { get; }

    /// <summary>
    /// Gets track language.
    /// </summary>
    public Language Language { get; }

    /// <summary>
    /// Gets a value indicating whether whether the track was automatically generated.
    /// </summary>
    public bool IsAutoGenerated { get; }

    /// <inheritdoc />
    [ExcludeFromCodeCoverage]
    public override string ToString() => $"CC Track ({this.Language})";
}